on: [push]

jobs:
  job_1:
    if: false

    name: Build and add image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file docker/web/githubDockerfile --tag myimagename:latest
      - name: Save the Docker image to file
        run: docker save -o myimage.tar myimagename:latest
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: myimage-tar
          path: myimage.tar

  job_2:
    if: false

    name: Run test on image
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download result for job 1
        uses: actions/download-artifact@v2
        with:
          name: myimage-tar
      - name: Install dependencies
        run: composer install
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v2
        with:
          name: myimage-tar
          path: math-homework.txt

  job_3:
    if: false

    name: Display results
    needs: job_2
    runs-on: macOS-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v2
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value
