on: [push]

jobs:
  job_1:
    name: Build and add image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file docker/web/githubDockerfile --tag myimagename:latest
      - name: Save the Docker image to file
        run: docker save -o myimage.tar myimagename:latest
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: myimagetar
          path: myimage.tar

  job_2:
    name: Run test on image
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact for job 1
        uses: actions/download-artifact@v2
        with:
          name: myimagetar
      - name: Load saved Docker image
        run: docker load -i myimage.tar
      - name: PHPCS tests
        id: phpcs
        run: docker run -it -d myimagename composer run-script cs-check | tee phpcsCheck.txt
        continue-on-error: true
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: PHPcsCheck
          path: phpcsCheck.txt
