on: [push]

jobs:
  job_1:
    name: Build and add image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file docker/web/githubDockerfile --tag myimagename:latest
      - name: Save the Docker image to file
        run: docker save -o myimage.tar myimagename:latest
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: myimagetar
          path: myimage.tar

  job_2:
    name: Run test on image
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download result for job 1
        uses: actions/download-artifact@v2
        with:
          name: myimagetar
      - name: Load saved Docker image
        run: docker load -i myimage.tar
      - name: Install dependencies
        run: composer install
